# Generated by Django 4.2.5 on 2024-09-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('birthday', models.DateField()),
                ('county', models.CharField(choices=[('US001', 'Autauga County'), ('US003', 'Baldwin County')], max_length=10)),
                ('interests', models.CharField(choices=[('sports', 'Sports'), ('music', 'Music'), ('technology', 'Technology'), ('reading', 'Reading'), ('traveling', 'Traveling')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
