# Generated by Django 4.2.5 on 2024-09-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='year_in_highschool',
            field=models.CharField(choices=[('pre-highschool', 'Pre-Highschool'), ('9th', '9th Grade'), ('10th', '10th Grade'), ('11th', '11th Grade'), ('12th', '12th Grade'), ('graduate', 'Highschool Graduate')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
