# Generated by Django 4.2.5 on 2024-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_user_birthday_user_year_in_highschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(choices=[('AL - US001', 'AL - Autauga County'), ('AL - US003', 'AL - Baldwin County')], max_length=10),
        ),
    ]
