# Generated by Django 4.2.5 on 2024-09-15 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connected_users',
            field=models.ManyToManyField(blank=True, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
