# Generated by Django 4.2.5 on 2024-09-15 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_opportunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='experience',
            field=models.CharField(choices=[('entry-level', 'Entry Level'), ('1-2-years', '1-2 years'), ('3-5-years', '3-5 years'), ('5-plus-years', '5+ years')], max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(choices=[('san-francisco', 'San Francisco, CA'), ('new-york', 'New York, NY'), ('austin', 'Austin, TX'), ('chicago', 'Chicago, IL'), ('remote', 'Remote')], max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('internship', 'Internship'), ('full-time', 'Full-time'), ('part-time', 'Part-time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
