# Generated by Django 4.2.5 on 2024-09-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_opportunity_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
